[project]
name = "speaches-cli"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Fedir Zadniprovskyi", email = "github.g1k56@simplelogin.com" }
]
requires-python = "==3.12.*"
dependencies = [
    "httpx>=0.27.2",
    "typer>=0.12.5",
]

[project.scripts]
speaches-cli = "speaches_cli.main:app"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
