name: lint
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "src/**"
      - "scripts/**"
      - "tests/**"
      - ".github/workflows/lint.yaml"
  pull_request:
    paths:
      - "src/**"
      - "scripts/**"
      - "tests/**"
      - ".github/workflows/lint.yaml"
jobs:
  ruff:
    runs-on: ubuntu-24.04-4core-x86
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/setup-uv@v6
        with:
          version: "latest"
          enable-cache: true
          activate-environment: true
      - run: uv python install 3.12
      - run: uv sync --extra dev
      - run: uv run ruff check .
      - run: uv run ruff format --check --diff .
  basedpyright:
    runs-on: ubuntu-24.04-4core-x86
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/setup-uv@v6
        with:
          version: "latest"
          enable-cache: true
          activate-environment: true
      - run: uv python install 3.12
      - run: uv sync --extra dev --extra ui
      - run: uv run basedpyright .
